<?php

namespace App\Services\Assets;

if(!defined('MAX_IMAGES_SIZE')) define('MAX_IMAGES_SIZE', 2000);

/**
 * NEWS IMAGES DIMENSION
 */
if(!defined('THUMBNAIL_NEWS_IMAGES_WIDTH')) define('THUMBNAIL_NEWS_IMAGES_WIDTH', 203);
if(!defined('THUMBNAIL_NEWS_IMAGES_HEIGHT')) define('THUMBNAIL_NEWS_IMAGES_HEIGHT', 208);

if(!defined('NEWS_IMAGES_WIDTH')) define('NEWS_IMAGES_WIDTH', 872);
if(!defined('NEWS_IMAGES_HEIGHT')) define('NEWS_IMAGES_HEIGHT', 503);

/**
 * PRODUCT IMAGES DIMENSION
 */
if(!defined('THUMBNAIL_PRODUCT_IMAGES_WIDTH')) define('THUMBNAIL_PRODUCT_IMAGES_WIDTH', 203);
if(!defined('THUMBNAIL_PRODUCT_IMAGES_HEIGHT')) define('THUMBNAIL_PRODUCT_IMAGES_HEIGHT', 208);

if(!defined('PRODUCT_IMAGES_WIDTH')) define('PRODUCT_IMAGES_WIDTH', 872);
if(!defined('PRODUCT_IMAGES_HEIGHT')) define('PRODUCT_IMAGES_HEIGHT', 503);

/**
 * PACKAGE IMAGES DIMENSION
 */
if(!defined('THUMBNAIL_PACKAGE_IMAGES_WIDTH')) define('THUMBNAIL_PACKAGE_IMAGES_WIDTH', 360);
if(!defined('THUMBNAIL_PACKAGE_IMAGES_HEIGHT')) define('THUMBNAIL_PACKAGE_IMAGES_HEIGHT', 433);

/**
 * GALLERY IMAGES DIMENSION
 */
if(!defined('THUMBNAIL_GALLERY_IMAGES_WIDTH')) define('THUMBNAIL_GALLERY_IMAGES_WIDTH', 400);
if(!defined('THUMBNAIL_GALLERY_IMAGES_HEIGHT')) define('THUMBNAIL_GALLERY_IMAGES_HEIGHT', 290);

if(!defined('GALLERY_IMAGES_WIDTH')) define('GALLERY_IMAGES_WIDTH', 872);
if(!defined('GALLERY_IMAGES_HEIGHT')) define('GALLERY_IMAGES_HEIGHT', 503);

/**
 * MAIN_BANNER IMAGES DIMENSION
 */
if(!defined('MAIN_BANNER_IMAGES_WIDTH')) define('MAIN_BANNER_IMAGES_WIDTH', 1920);
if(!defined('MAIN_BANNER_IMAGES_HEIGHT')) define('MAIN_BANNER_IMAGES_HEIGHT', 1018);